apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJSnMrUFoxZ20vZ3N3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBeE1ESXdPVEl6TVRWYUZ3MHpOVEV5TXpFd09USTRNVFZhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURQaWFGendDSWVUcUhQR3NtQUFhQm13SG8xZnJSOWNqK1QyWVJidTJBZk94VzRxL3RNUVJxNlNXL1MKN2l4R3ZCcjJ0L3krZUJXZ1AzQ0VxQlg5bmpxTERNZEQxdmEvT2hQeUdQaHBuekdvYUxQQlJzRmNDNklzNTYwSwpMZ09xSlNOTTg2bnhlL05raUU1cjFTUlhqMnhWVXdONGFFMlgybDNCRU1aZE1uYTdhWUZEWGJXU0RPdi9GQURhCmZLdThWTHJhZCtESHFaK25DSXUyblprMXAwVlBCWDNTbmxhOXNqUVhUdnpBRmQwcFlsY2dLQ093ZGd2YXJlSVMKYUN1L3A3a3NDZmphUzV1aVAzZzNPUjh3K2lZallsSWtZOTNJd1IvenNGMU9oOEFCbklsbjRQb0c5b3Rtb2hieApTb3h1L0JYYmZWbWlxZHBRSkRqRW44MWlqNkd6QWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUdlV0Unp0WmoyUmRQSzBoUGVUdXFFVXE4UDJ6QVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQUl5LzhVTmhoagpvQ0JweU9HQ2hNQXBWZVpaUm1lZ0k3VmFpbXVrRExOK0xUSm5MSE92RFBkNXgxb1lhTHkydTRYLzlNSGhodDBOCkcrMHJlU2VrNXgvQkhmOERFeDhhVTZDZmRPVGMvd3VNK3pGd1dFbmdUTGF2a21QL1FqQlJlWnc1czZuQk8xYWgKLy9nTVBqR24zSHgxbHozek9JNE5MRzNuVjh3Qnp3VFlWdDhTd1QyYXJxR2UvMDdWcndjdTlrY0hMS0Z6djB4Vgp4Y1MwdU5WaGlwTUlsY0sxZERzTzgwMThmQ1VkTlh5eUloejJCb3E3ZkZudkNWT2llcnY4Ny9ubWtSYWNaZEU2CjhiWU02dStRTGx0dUQ3a2VtcVYvZHUyaXk5THR1djRtNGNaS2VhUWpTbWRuaUlqNGk4dE1XUHpsOTByUUJlSEUKVmxuM2J6SHZjWEh0Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://653ACBFA325E68673CF206E25FEF3899.gr7.us-west-2.eks.amazonaws.com
  name: arn:aws:eks:us-west-2:257394496890:cluster/tooling-eks-cluster
contexts:
- context:
    cluster: arn:aws:eks:us-west-2:257394496890:cluster/tooling-eks-cluster
    user: arn:aws:eks:us-west-2:257394496890:cluster/tooling-eks-cluster
  name: arn:aws:eks:us-west-2:257394496890:cluster/tooling-eks-cluster
current-context: arn:aws:eks:us-west-2:257394496890:cluster/tooling-eks-cluster
kind: Config
preferences: {}
users:
- name: arn:aws:eks:us-west-2:257394496890:cluster/tooling-eks-cluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-west-2
      - eks
      - get-token
      - --cluster-name
      - tooling-eks-cluster
      - --output
      - json
      command: aws
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
