apiVersion: v1
kind: Secret
metadata:
  name: titanic-secrets
type: Opaque
stringData:
  POSTGRES_USER: titanic_user
  POSTGRES_PASSWORD: supersecret
  DATABASE_URL: postgresql://titanic_user:supersecret@postgres:5432/titanic
