name: CD to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      KUBE_CONFIG_B64: ${{ secrets.KUBE_CONFIG_B64 }}  # your EKS kubeconfig
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      IMAGE_NAME: anyankpele/titanic-api
      IMAGE_TAG: latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG

      - name: Set up kubectl
        run: |
          mkdir -p $HOME/.kube
          echo "$KUBE_CONFIG_B64" | base64 --decode > $HOME/.kube/config
          kubectl version --client

      - name: Deploy to EKS
        run: |
          kubectl set image deployment/titanic-api titanic-api=$IMAGE_NAME:$IMAGE_TAG --record
          kubectl rollout status deployment/titanic-api
          kubectl get pods
